arch = [
  "act",
  "alsa-utils",
  "anytype-bin",
  "arandr",
  "archlinux-themes-sddm",
  "arm-none-eabi-gdb",
  "audiorelay",
  "base",
  "base-devel",
  "borg",
  "btop",
  "chezmoi",
  "claude-code",
  "codelldb-bin",
  "cronie",
  "direnv",
  "docker",
  "dungeondraft",
  "firefox",
  "fuse2",
  "ghostty",
  "git",
  "github-cli",
  "go",
  "graphicsmagick",
  "graphviz",
  "gwakeonlan",
  "hyprland",
  "hyprlock",
  "hyprsunset",
  "imagemagick",
  "inkscape",
  "jujutsu",
  "just",
  "kew",
  "kitty",
  "libheif",
  "libreoffice-fresh",
  "linux",
  "linux-firmware",
  "metapac",
  "minecraft-launcher",
  "minicom",
  "mpd",
  "ncmpcpp",
  "neovim",
  "networkmanager",
  "networkmanager-openconnect",
  "networkmanager-openvpn",
  "npm",
  "openssh",
  "otf-aurulent-nerd",
  "otf-codenewroman-nerd",
  "otf-comicshanns-nerd",
  "otf-commit-mono-nerd",
  "otf-droid-nerd",
  "otf-firamono-nerd",
  "otf-geist-mono-nerd",
  "otf-hasklig-nerd",
  "otf-hermit-nerd",
  "otf-monaspace-nerd",
  "otf-opendyslexic-nerd",
  "otf-overpass-nerd",
  "parallel",
  "paru",
  "paru-debug",
  "pdftk",
  "pellets",
  "piper-tts-bin",
  "piper-voices-common",
  "piper-voices-en-us",
  "pipewire-alsa",
  "pipewire-docs",
  "pipewire-pulse",
  "qgis",
  "qt5-declarative",
  "refind",
  "scons",
  "sddm-git",
  "sof-firmware",
  "speech-dispatcher",
  "steam",
  "steamtinkerlaunch",
  "sudo",
  "thunar",
  "thunderbird",
  "ttf-0xproto-nerd",
  "ttf-3270-nerd",
  "ttf-agave-nerd",
  "ttf-anonymouspro-nerd",
  "ttf-arimo-nerd",
  "ttf-bigblueterminal-nerd",
  "ttf-bitstream-vera-mono-nerd",
  "ttf-cascadia-code-nerd",
  "ttf-cascadia-mono-nerd",
  "ttf-cousine-nerd",
  "ttf-d2coding-nerd",
  "ttf-daddytime-mono-nerd",
  "ttf-dejavu-nerd",
  "ttf-envycoder-nerd",
  "ttf-fantasque-nerd",
  "ttf-firacode-nerd",
  "ttf-go-nerd",
  "ttf-gohu-nerd",
  "ttf-hack-nerd",
  "ttf-heavydata-nerd",
  "ttf-iawriter-nerd",
  "ttf-ibmplex-mono-nerd",
  "ttf-inconsolata-go-nerd",
  "ttf-inconsolata-lgc-nerd",
  "ttf-inconsolata-nerd",
  "ttf-intone-nerd",
  "ttf-iosevka-nerd",
  "ttf-iosevkaterm-nerd",
  "ttf-iosevkatermslab-nerd",
  "ttf-jetbrains-mono-nerd",
  "ttf-lekton-nerd",
  "ttf-liberation-mono-nerd",
  "ttf-lilex-nerd",
  "ttf-martian-mono-nerd",
  "ttf-meslo-nerd",
  "ttf-monofur-nerd",
  "ttf-monoid-nerd",
  "ttf-mononoki-nerd",
  "ttf-mplus-nerd",
  "ttf-nerd-fonts-symbols",
  "ttf-nerd-fonts-symbols-mono",
  "ttf-noto-nerd",
  "ttf-profont-nerd",
  "ttf-proggyclean-nerd",
  "ttf-recursive-nerd",
  "ttf-roboto-mono-nerd",
  "ttf-sharetech-mono-nerd",
  "ttf-sourcecodepro-nerd",
  "ttf-space-mono-nerd",
  "ttf-terminus-nerd",
  "ttf-tinos-nerd",
  "ttf-ubuntu-mono-nerd",
  "ttf-ubuntu-nerd",
  "ttf-victor-mono-nerd",
  "ttf-zed-mono-nerd",
  "uwsm",
  "vi",
  "vim",
  "waybar",
  "wofi",
  "xdg-desktop-portal",
  "xdg-desktop-portal-hyprland",
  "yay-debug",
  "zip",
  "zoom",
  "zotero-bin",
  "zsh",
]
