arch = [
  "act",  # Run GH Actions from the CLI!
  "alsa-utils",  # ALSA sound support
  "anytype-bin",  # Notion, but local, but secured, but german
  "archlinux-themes-sddm", # login screen theme
  "arm-none-eabi-gdb",  # ARM debugger
  "audiorelay",  # stream audio from one device to another
  "base",  # base packages
  "base-devel",  # base development packages
  "borg",  # deduplicating backup tool
  "btop",  # top, but cooler (htop), but sleeker
  "chezmoi",  # dotfiles manager
  "claude-code",  # I literally have all the contempt for myself and deserve death
  "codelldb-bin",  # lldb for dap debugging
  "cronie",  # cron
  "direnv",  # environment manager
  "docker",  # containerize everything
  "dungeondraft",  # Dungeon Crawl Stone Soup
  "firefox",  # web browser
  "fuse2",  # Interface for userspace programs to export a filesystem to the Linux kernel
  "ghostty",  # terminal, but better (and written in zig!!)
  "git",  # git
  "github-cli",  # I hate microsoft, one day I will delete this
  "go",  # golang, damn it google, don't design by committee again
  "graphicsmagick",  # Image magick, but better
  "graphviz",  # dot my love...
  "gwakeonlan",  # wake on lan
  "hyprland",  # sleek, tiling, wayland compositor (did i mention it's sleek?)
  "hyprlock",  # lock screen for the sleekest of compositors
  "hyprsunset",  # sleep timer for the sleekest of compositors
  "imagemagick",  # need this for graphicsmagick
  "inkscape",  # svg editor
  "jujutsu",  # git, but... sleeker
  "just",  # command runner, very nice
  "kew",  # terminal audio player
  "libheif",  # compression (HEIF) support
  "libreoffice-fresh",  # office suite
  "linux",  # kernel
  "linux-firmware",  # firmware
  "metapac",  # metapackage manager
  "minecraft-launcher",  # minecraft launcher
  "minicom",  # serial terminal
  "mpd",  # music player daemon
  "ncmpcpp",  # music player client
  "networkmanager",  # network manager
  "networkmanager-openconnect",  # network manager openconnect plugin
  "networkmanager-openvpn",  # network manager openvpn plugin
  "npm",  # node package manager, death to javascript
  "openssh",  # ssh
  "otf-aurulent-nerd",  # nerd fonts......
  "otf-codenewroman-nerd",
  "otf-comicshanns-nerd",
  "otf-commit-mono-nerd",
  "otf-droid-nerd",
  "otf-firamono-nerd",
  "otf-geist-mono-nerd",
  "otf-hasklig-nerd",
  "otf-hermit-nerd",
  "otf-monaspace-nerd",
  "otf-opendyslexic-nerd",
  "otf-overpass-nerd",
  "parallel",  # run multiple commands in parallel
  "paru",  # AUR helper
  "paru-debug",  # AUR helper
  "pdftk",  # all the pdf utils
  "piper-tts-bin",  # text to speech
  "piper-voices-common",
  "piper-voices-en-us",
  "pipewire-alsa",  # audio stuff for pipewire
  "pipewire-docs",
  "pipewire-pulse",
  "qgis",  # GIS
  "qt5-declarative",  # what a cute framework
  "refind",  # EFI boot manager, it's quite nice
  "scons",  # a bad build system for fools
  "sddm-git",  # login manager
  "sof-firmware",  # firmware
  "speech-dispatcher",  # text to speech
  "steam",  # hmmm. should I remove this? Just one more hour I swear....
  "steamtinkerlaunch",  # steam mod launcher
  "sudo",  # I AM GOD
  "thunar",  # file manager
  "thunderbird",  # email
  "ttf-0xproto-nerd",  # nerd fonts
  "ttf-3270-nerd",
  "ttf-agave-nerd",
  "ttf-anonymouspro-nerd",
  "ttf-arimo-nerd",
  "ttf-bigblueterminal-nerd",
  "ttf-bitstream-vera-mono-nerd",
  "ttf-cascadia-code-nerd",
  "ttf-cascadia-mono-nerd",
  "ttf-cousine-nerd",
  "ttf-d2coding-nerd",
  "ttf-daddytime-mono-nerd",
  "ttf-dejavu-nerd",
  "ttf-envycoder-nerd",
  "ttf-fantasque-nerd",
  "ttf-firacode-nerd",
  "ttf-go-nerd",
  "ttf-gohu-nerd",
  "ttf-hack-nerd",
  "ttf-heavydata-nerd",
  "ttf-iawriter-nerd",
  "ttf-ibmplex-mono-nerd",
  "ttf-inconsolata-go-nerd",
  "ttf-inconsolata-lgc-nerd",
  "ttf-inconsolata-nerd",
  "ttf-intone-nerd",
  "ttf-iosevka-nerd",
  "ttf-iosevkaterm-nerd",
  "ttf-iosevkatermslab-nerd",
  "ttf-jetbrains-mono-nerd",
  "ttf-lekton-nerd",
  "ttf-liberation-mono-nerd",
  "ttf-lilex-nerd",
  "ttf-martian-mono-nerd",
  "ttf-meslo-nerd",
  "ttf-monofur-nerd",
  "ttf-monoid-nerd",
  "ttf-mononoki-nerd",
  "ttf-mplus-nerd",
  "ttf-nerd-fonts-symbols",
  "ttf-nerd-fonts-symbols-mono",
  "ttf-noto-nerd",
  "ttf-profont-nerd",
  "ttf-proggyclean-nerd",
  "ttf-recursive-nerd",
  "ttf-roboto-mono-nerd",
  "ttf-sharetech-mono-nerd",
  "ttf-sourcecodepro-nerd",
  "ttf-space-mono-nerd",
  "ttf-terminus-nerd",
  "ttf-tinos-nerd",
  "ttf-ubuntu-mono-nerd",
  "ttf-ubuntu-nerd",
  "ttf-victor-mono-nerd",
  "ttf-zed-mono-nerd",
  "uwsm",  # window manager for the sleekest of the sleekest sleekers
  "vi",  # and God said, "let there be vi"
  "vim",  # then he said, "I can do better"
  "neovim",  # and jesus said, "Old man, you just watch"
  "waybar",  # status bar for the sleeeekest sleekiest slkeeeker sklkslkdfjfs
  "wofi",  # application launcher for the sleekskeelk skleekeeeek sdjkjflsjljahhdigishdfsh
  "xdg-desktop-portal",  # desktop integration
  "xdg-desktop-portal-hyprland",  # desktop integration for slk folks
  "zip",  # gotta   c o m p r e s s    (except it's windows ugh)
  "zoom",  # I know you're watching Xi. I know you're watching....
  "zotero-bin",  # bibliographies for awesome researchers :)
  "zsh",  # my favorite sh
]
