return   {
"nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "c",
      "lua",
      "vim",
      "vimdoc",
      "query",
      "bash",
      "cmake",
      "cpp",
      "dockerfile",
      "gitcommit",
      "git_rebase",
      "html",
      "json",
      "llvm",
      "markdown",
      "markdown_inline",
      "make",
      "python",
      "tablegen",
      "yaml",
    },
  },
}
